
name: Manual Instagram Data Processor

# NO automatic scheduling - only manual triggers
on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      target_row:
        description: 'Row number to process (optional)'
        required: false
        type: string

  # API trigger for Apps Script
  repository_dispatch:
    types: [manual-instagram-extraction]

jobs:
  manual-processing:
    runs-on: ubuntu-latest
    name: Manual Instagram Data Processing
    timeout-minutes: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install instaloader gspread google-auth google-auth-oauthlib google-auth-httplib2 pytz

    - name: Process Manual Instagram Request
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        TARGET_ROW: ${{ github.event.inputs.target_row }}
      run: python instagram_manual_processor.py
      timeout-minutes: 8

    - name: Manual Processing Summary
      run: |
        echo "Manual Instagram data processing completed"
        echo "Fresh session created for this request"
        echo "Check your Google Sheet for updated data"
