
name: Persistent Instagram Data Extractor

on:
  # Automatic processing every 10 minutes
  schedule:
    - cron: '*/10 * * * *'

  # Manual trigger from GitHub or Apps Script
  workflow_dispatch:

  # API trigger for Apps Script integration
  repository_dispatch:
    types: [instagram-extraction]

jobs:
  persistent-extraction:
    runs-on: ubuntu-latest
    name: Persistent Instagram Data Processing
    timeout-minutes: 45

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install instaloader gspread google-auth google-auth-oauthlib google-auth-httplib2 pytz

    - name: Execute Persistent Instagram Extractor
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
      run: python instagram_extractor_persistent.py
      timeout-minutes: 40

    - name: Processing Summary
      run: |
        echo "✅ PERSISTENT Instagram data extraction completed"
        echo "💪 System tried multiple times until ALL URLs were processed"
        echo "📊 Check your Google Sheet for updated data with IST timestamps"
        echo "🔄 Failed URLs were automatically retried"
